version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:Qwerty12@postgres:5432/brd  # Обновленное подключение к базе данных

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty12
      POSTGRES_DB: brd